# Generated by Django 3.2.3 on 2021-05-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairmarkit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=40, verbose_name='Жанр'),
        ),
    ]
